version: '3'
services:
  keyserver:
    image: "delta1925/simple-wkd"
    restart: always
    ports:
      - 127.0.0.1:8080:8080
    environment:
      - RUST_LOG=debug
    volumes:
      - ./config.toml:/wkd/config.toml
      - wkd-data:/wkd/data
      - wkd-logs:/wkd/logs

volumes:
  wkd-data:
  wkd-logs:
