variant = "Advanced"
max_age = 900
cleanup_interval = 21600
allowed_domains = ["example.org", "example.com"]
port = 8080
bind_host = "0.0.0.0"
external_url = "http://localhost:8080"

[mail_settings]
smtp_host = "mail.example.org"
smtp_username = "keyservice"
smtp_password = "verysecurepassword"
smtp_port = 465
smtp_tls = "Tls"
mail_from = "key-submission@example.org"
mail_subject = "Please confirm to %a your public key"